services:
  cidindexer:
    image: ghcr.io/gipplab/cid-indexer-ipfs:latest
    restart: unless-stopped
    ports:
      - "8384:8384"
    environment:
      SAIA_API_KEY: "your-key-here"
    volumes:
      - cidindexer-data:/data

volumes:
  cidindexer-data:
